version: '3.1'
services:
  db:
    image: mariadb:10.11.2
    container_name: github-adapter-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - GITHUB_ADAPTER_DB_VOLUME:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: empik
      MYSQL_USER: empik-user
      MYSQL_PASSWORD: empik-user
      MYSQL_DATABASE: github-adapter
    ports:
      - "3307:3306"
volumes:
  GITHUB_ADAPTER_DB_VOLUME: